name: Get Release Name
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to upload"
        required: true
      pypi_repo:
        description: "Repo to upload to (Test PyPI or PyPI)"
        default: "testpypi"
        required: true
env:
  VERSION: ${{ github.event.inputs.version }}
jobs:
  print-values:
    name: Print Input and Release Version
    runs-on: ubuntu-latest
    steps:
      - name: Print all values
        run: |
          echo $VERSION
          echo $GITHUB_REF
          echo ${GITHUB_REF:10}
      
